spring.application.name=e-commerce
server.servlet.context-path=/hairfit

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/wig-store?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=3600
application.security.jwt.refresh-expiration=360000

# Mail Configuration (Using Brevo SMTP)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME:YOUR_BREVO_REGISTERED_EMAIL}
spring.mail.password=${MAIL_PASSWORD:YOUR_BREVO_SMTP_KEY_OR_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
app.mail.from=${MAIL_FROM:YOUR_VERIFIED_BREVO_SENDER_EMAIL}
